apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danblacklist/argoCD-demo.git
    targetRevision: HEAD
    path: nginx-service
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 51.2.0
    chart: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
