apiVersion: v1
data:
  index.html: |
    <html>
    <h1>NGINX DANISH</h1>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-index-html-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    deployment-name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx
        deployment-name: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/index.html
            name: nginx-conf
            subPath: index.html
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-index-html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    deployment-name: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
