apiVersion: v1
data:
  index.html: |
    <html>
    <h1>NGINX DANISH</h1>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-index-html-configmap
---
apiVersion: v1
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;

      location /app {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }    
      
      location /metrics {
          stub_status;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-conf-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    deployment-name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      deployment-name: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx
        deployment-name: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/index.html
            name: nginx-index
            subPath: index.html
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-conf
            subPath: default.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: nginx-index
          configMap:
            name: nginx-index-html-configmap
        - name: nginx-conf
          configMap:
            name: nginx-conf-configmap
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-nginx-application
  name: nginx-service
  namespace: default
spec:
  clusterIP: 10.100.125.102
  clusterIPs:
  - 10.100.125.102
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deployment-name: nginx-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: playground-cluster-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 80
